// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TsheThauLoo.Data;

#nullable disable

namespace TsheThauLoo.Data.Migrations
{
    [DbContext(typeof(TsheThauLooDbContext))]
    partial class TsheThauLooDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.School.College", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colleges");

                    b.HasData(
                        new
                        {
                            Id = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Name = "工程與科學學院"
                        },
                        new
                        {
                            Id = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Name = "商學院"
                        },
                        new
                        {
                            Id = "ZJQvZKxgdLSVgeAjnIBNkLUoD",
                            Name = "經營管理學院"
                        },
                        new
                        {
                            Id = "Bem4x4ONNKfMVLge333K97tpP",
                            Name = "人文社會學院"
                        },
                        new
                        {
                            Id = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Name = "資訊電機學院"
                        },
                        new
                        {
                            Id = "QGqpVsNzjcusLw2lisuECLEaT",
                            Name = "建設學院"
                        },
                        new
                        {
                            Id = "iQJHwPwg4VAFwjXDJPVH2wtE0",
                            Name = "金融學院"
                        },
                        new
                        {
                            Id = "9xP6LTPTAcSWkRF6cx9Iq7cDv",
                            Name = "國際科技與管理學院"
                        },
                        new
                        {
                            Id = "woYRzMjOYVT0LlwVEvqarGaoS",
                            Name = "建築專業學院"
                        },
                        new
                        {
                            Id = "ggRSStSxsHsmiT3yvftunUmCm",
                            Name = "創能學院"
                        });
                });

            modelBuilder.Entity("TsheThauLoo.Entities.School.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("CollegeId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int>("Degree")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = "E4TLO6Rlk845z2oUdcY4Iv06m",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 0,
                            Name = "機械與電腦輔助工程學系"
                        },
                        new
                        {
                            Id = "Ef1eMd6LtaZP03ZpODKQnkPrr",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 0,
                            Name = "纖維與複合材料學系"
                        },
                        new
                        {
                            Id = "1aVlra0qikcAV2JRV7TMRp7iI",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 0,
                            Name = "工業工程與系統管理學系"
                        },
                        new
                        {
                            Id = "lziprhEYXoNTIaifDM1jg2aDl",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 0,
                            Name = "化學工程學系"
                        },
                        new
                        {
                            Id = "V2mx0chIIFPm47C9QShaDcOse",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 0,
                            Name = "應用數學系"
                        },
                        new
                        {
                            Id = "t6iTp3drNHeKklGvntaCj4Y3x",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 0,
                            Name = "航太與系統工程學系"
                        },
                        new
                        {
                            Id = "jipCkuWAE0Du3bpRCRx8bsh6a",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 0,
                            Name = "環境工程與科學學系"
                        },
                        new
                        {
                            Id = "qqt2F3NiHmRZC3JQ2swBtlkAU",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 0,
                            Name = "材料科學與工程學系"
                        },
                        new
                        {
                            Id = "hpp8lWqxvHlO4UL5Jv8vIiyGV",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 0,
                            Name = "光電科學與工程學系"
                        },
                        new
                        {
                            Id = "M7uQ44lkDMXGUXTVIllFHIu0U",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 0,
                            Name = "精密系統設計學士學位學程"
                        },
                        new
                        {
                            Id = "W7hjovei6RLK2AL7i1wZAFaDM",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "機械與電腦輔助工程學系"
                        },
                        new
                        {
                            Id = "O9obZd6NxvP91r0V1HizlRmzx",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "纖維與複合材料學系"
                        },
                        new
                        {
                            Id = "vmfuonsJ6lEsGrfg1zor4wgjT",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "工業工程與系統管理學系"
                        },
                        new
                        {
                            Id = "Td6VsS8gaAJJFiqqG9rYtb8Ka",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "化學工程學系"
                        },
                        new
                        {
                            Id = "ShJZ82POiUdB5PCThigo9NHCJ",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "數據科學碩士學位學程"
                        },
                        new
                        {
                            Id = "MzTRWWzVUx4We6TIkh4N6UxzH",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "航太與系統工程學系"
                        },
                        new
                        {
                            Id = "8Qxn6SnBisKk0zL5ZaCNHzHNU",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "環境工程與科學學系"
                        },
                        new
                        {
                            Id = "wftcQpHOTzWoLLrA43mbVuSij",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "材料科學與工程學系"
                        },
                        new
                        {
                            Id = "ELz9CQQsBKPWDhP8dblVbBF6A",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "光電科學與工程學系"
                        },
                        new
                        {
                            Id = "E5JhN19uEM9iT39gupupFtKqb",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "電聲碩士學位學程"
                        },
                        new
                        {
                            Id = "mZItIEcOqGsf2D1CDB75ATNNb",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "綠色能源科技碩士學位學程"
                        },
                        new
                        {
                            Id = "z2GeW6JHLUxUyZp6ej88KdJ2z",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "智能製造與工程管理碩士在職學位學程"
                        },
                        new
                        {
                            Id = "27kTZ7FpUueqEEXZYr5VFvjaS",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 1,
                            Name = "應用數學系"
                        },
                        new
                        {
                            Id = "alfxjGB18v40cO9P1exRs9bch",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 2,
                            Name = "材料科學與工程學系"
                        },
                        new
                        {
                            Id = "7FSHfS7OyuHS5Dz0BoHkNvXSN",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 2,
                            Name = "化學工程學系"
                        },
                        new
                        {
                            Id = "hclqd3Hyx4ibaMgdNbj4eWqwu",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 2,
                            Name = "纖維與複合材料學系"
                        },
                        new
                        {
                            Id = "fHZZYLLRYQfq5zVpWYw2loUei",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 2,
                            Name = "環境工程與科學學系"
                        },
                        new
                        {
                            Id = "ZIt17vZJhZYKuNu8uip8mpL4k",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 2,
                            Name = "機械與航空工程博士學位學程"
                        },
                        new
                        {
                            Id = "ZMbKwvFHC8uItgeEHlBXvEHKU",
                            CollegeId = "orgyTzqhLxdCWYZrjnfNMwE88",
                            Degree = 2,
                            Name = "工業工程與系統管理學系"
                        },
                        new
                        {
                            Id = "CsgftORomoxhN0uKAtYU7smKM",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "會計學系"
                        },
                        new
                        {
                            Id = "cvje3HNALJWaFcUJfhOv1BT7f",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "企業管理學系"
                        },
                        new
                        {
                            Id = "DqV7WwMlTC5QCzi5rCvIh6hIm",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "國際經營與貿易學系"
                        },
                        new
                        {
                            Id = "DZCrDRmTMETLmS41PoVLReTcT",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "財稅學系"
                        },
                        new
                        {
                            Id = "JdbXmSGoUw4piAV9Ytx2AHq6G",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "統計學系"
                        },
                        new
                        {
                            Id = "0yn8nTHeTq33d7r8HGT972YKf",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "經濟學系"
                        },
                        new
                        {
                            Id = "YB0mkKPStKJuB1LIxf7YW1ZPf",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "合作經濟暨社會事業經營學系"
                        },
                        new
                        {
                            Id = "6hqWk2IvTqFH56Ul0UCmptGmu",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "行銷學系"
                        },
                        new
                        {
                            Id = "q3nlnIpsjsxXYpgNKlMttHXea",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "國際企業管理全英語學士學位學程"
                        },
                        new
                        {
                            Id = "SJNlUG18aLT02IvfQgsXTuK2H",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "商學進修學士學位學程"
                        },
                        new
                        {
                            Id = "de1Jnf9QD3gvMTPRwz4NxhVDw",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 0,
                            Name = "商學進修學士班"
                        },
                        new
                        {
                            Id = "JkL8NFfUSTFriQGFfhftPkmpO",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "會計學系"
                        },
                        new
                        {
                            Id = "1KMvherE36HxeETXr3xse9HZk",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "企業管理學系"
                        },
                        new
                        {
                            Id = "leYi4G3rCzMLNDkQuA2F4DcH1",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "國際經營與貿易學系"
                        },
                        new
                        {
                            Id = "JlZcnZDK4kpGlRLUPr6fk9xzb",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "財稅學系"
                        },
                        new
                        {
                            Id = "DlcGMcK0dUdA5gRwdxmbM7oZG",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "統計學系"
                        },
                        new
                        {
                            Id = "fhbrQBPIlbOHqqDpVel1bofqj",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "經濟學系"
                        },
                        new
                        {
                            Id = "DEH5ixlYgCzxPcE1Npro3xXef",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "合作經濟暨社會事業經營學系"
                        },
                        new
                        {
                            Id = "WWW1UII5bCGy6mZYliLWqTb3Y",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "行銷學系"
                        },
                        new
                        {
                            Id = "DMYlpsYuNEgYb49p4pQpqa89V",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "財經法律研究所"
                        },
                        new
                        {
                            Id = "qDSwwlratoGaz84ii6LibEFs2",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "科技管理碩士學位學程"
                        },
                        new
                        {
                            Id = "5IhwNG2y1wlsaIfty7gyggsuL",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "商學專業碩士在職學位學程"
                        },
                        new
                        {
                            Id = "WRxZ6INKBMk3Luk9pdlxWVbD8",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 1,
                            Name = "商學院商學專業碩士在職專班"
                        },
                        new
                        {
                            Id = "IgGhCciiJgrkqhSlPwFAURR2A",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 2,
                            Name = "統計學系"
                        },
                        new
                        {
                            Id = "Gl9ruZax8lgwKo8FrscM7G9wy",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 2,
                            Name = "經濟學系"
                        },
                        new
                        {
                            Id = "d0tSW85jXda65OgJG7QvJqA87",
                            CollegeId = "0dI3qiJ4paEsZAffJarvrZtL3",
                            Degree = 2,
                            Name = "商學博士學位學程"
                        },
                        new
                        {
                            Id = "a8qq4y4du8qQFQ1E47zkSxRFj",
                            CollegeId = "ZJQvZKxgdLSVgeAjnIBNkLUoD",
                            Degree = 1,
                            Name = "經營管理碩士在職學位學程"
                        },
                        new
                        {
                            Id = "vaGAaenkbRlrHWXbU6GanCA2a",
                            CollegeId = "ZJQvZKxgdLSVgeAjnIBNkLUoD",
                            Degree = 1,
                            Name = "經營管理碩士在職專班"
                        },
                        new
                        {
                            Id = "wdVJDbdDmhz27blrxFLKIELqj",
                            CollegeId = "Bem4x4ONNKfMVLge333K97tpP",
                            Degree = 0,
                            Name = "中國文學系"
                        },
                        new
                        {
                            Id = "7CoXdHz2bWFuTk7xE4jD3O626",
                            CollegeId = "Bem4x4ONNKfMVLge333K97tpP",
                            Degree = 0,
                            Name = "外國語文學系"
                        },
                        new
                        {
                            Id = "Z3JpsBrwJF8BnPjrLnKyB1oHs",
                            CollegeId = "Bem4x4ONNKfMVLge333K97tpP",
                            Degree = 0,
                            Name = "人文社會學士學位學程"
                        },
                        new
                        {
                            Id = "fDaJWG0j4tZKJD7LZxf84ERNh",
                            CollegeId = "Bem4x4ONNKfMVLge333K97tpP",
                            Degree = 1,
                            Name = "中國文學系"
                        },
                        new
                        {
                            Id = "quIjrAqQ12NKLW2LL0DIDbMdS",
                            CollegeId = "Bem4x4ONNKfMVLge333K97tpP",
                            Degree = 1,
                            Name = "外國語文學系"
                        },
                        new
                        {
                            Id = "XqGWrO7VR16BZRlJBbOixhfAz",
                            CollegeId = "Bem4x4ONNKfMVLge333K97tpP",
                            Degree = 1,
                            Name = "歷史與文物研究所"
                        },
                        new
                        {
                            Id = "VTUjz812ZDfz7dcl6oNf8yHqJ",
                            CollegeId = "Bem4x4ONNKfMVLge333K97tpP",
                            Degree = 1,
                            Name = "公共事務與社會創新研究所"
                        },
                        new
                        {
                            Id = "Dh4oZEA9zkc3ACZaRM9VtdQBH",
                            CollegeId = "Bem4x4ONNKfMVLge333K97tpP",
                            Degree = 1,
                            Name = "文化與社會創新碩士學位學程"
                        },
                        new
                        {
                            Id = "2Ao6OxweQUKatNTwLqL1SWUIx",
                            CollegeId = "Bem4x4ONNKfMVLge333K97tpP",
                            Degree = 1,
                            Name = "公共事務與社會創新碩士在職學位學程"
                        },
                        new
                        {
                            Id = "OYM5tHafmDVssmZLQHtK5Sit2",
                            CollegeId = "Bem4x4ONNKfMVLge333K97tpP",
                            Degree = 2,
                            Name = "中國文學系"
                        },
                        new
                        {
                            Id = "oW8SWY9EukV5Ywid5WrxTVHau",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 0,
                            Name = "資訊工程學系"
                        },
                        new
                        {
                            Id = "90GsDYOXGVH4l3KVGxYol1W2o",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 0,
                            Name = "電子工程學系"
                        },
                        new
                        {
                            Id = "rxjYhZnZzLRGlbkWdLbRpGCgD",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 0,
                            Name = "電機工程學系"
                        },
                        new
                        {
                            Id = "HZToLVKBIxKg1pcG4s8YqT3eo",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 0,
                            Name = "自動控制工程學系"
                        },
                        new
                        {
                            Id = "RLi7RVRW3IUQCOCLQQZIUrfIs",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 0,
                            Name = "通訊工程學系"
                        },
                        new
                        {
                            Id = "HjMLEuFapCEXLd1M1TUxLd9sL",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 0,
                            Name = "資訊電機學院學士班"
                        },
                        new
                        {
                            Id = "5kPtkwk26CsmYF92Yjm7eFS25",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 1,
                            Name = "資訊工程學系"
                        },
                        new
                        {
                            Id = "nONXyEz08bBBJdn66Cvq3oMIt",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 1,
                            Name = "電子工程學系"
                        },
                        new
                        {
                            Id = "5zNvuPL5SJVEYi3a10zPEQO8p",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 1,
                            Name = "電機工程學系"
                        },
                        new
                        {
                            Id = "2L99Mx5zbL0nVEVZ5SQwrdvPp",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 1,
                            Name = "自動控制工程學系"
                        },
                        new
                        {
                            Id = "dPxcwXdkxCCGd02FuI0mhswrG",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 1,
                            Name = "通訊工程學系"
                        },
                        new
                        {
                            Id = "oJ9mWh0t2QzrKyVbqOKy6Uxla",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 1,
                            Name = "生醫資訊暨生醫工程碩士學位學程"
                        },
                        new
                        {
                            Id = "PZBs3lnNWZ1KJKiC91m09gRwG",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 1,
                            Name = "光電能源與視覺科技碩士在職專班"
                        },
                        new
                        {
                            Id = "5BMNEb4vjpRMSBwQZP3zCDnpB",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 1,
                            Name = "視光科技碩士在職學位學程"
                        },
                        new
                        {
                            Id = "E21Gz0eq5OnXxHgLXGJsYIKmn",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 1,
                            Name = "資訊電機工程碩士在職學位學程"
                        },
                        new
                        {
                            Id = "5mecRMeCuQzDF9PrBjSUsCDtc",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 1,
                            Name = "資訊電機工程碩士在職專班"
                        },
                        new
                        {
                            Id = "12Hz7QGyAnqdqT7hMVpIX3ouB",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 2,
                            Name = "資訊工程學系"
                        },
                        new
                        {
                            Id = "ZOog2nEV9O1zrMv4DVRyQU55I",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 2,
                            Name = "電機與通訊工程博士學位學程"
                        },
                        new
                        {
                            Id = "6AEGePPNeOcgGUdevl7XD9v69",
                            CollegeId = "if0gyRKzbTjqNb2BCn89dAVfA",
                            Degree = 2,
                            Name = "智慧聯網產業博士學位學程"
                        },
                        new
                        {
                            Id = "QxgyniralF6EKpnroqXQdcCtS",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 0,
                            Name = "土木工程學系"
                        },
                        new
                        {
                            Id = "3qR46zhPrQyWVkMfXVWT5ikFs",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 0,
                            Name = "水利工程與資源保育學系"
                        },
                        new
                        {
                            Id = "9cQA7y6zMOXj4VrpoNbukepq3",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 0,
                            Name = "運輸與物流學系"
                        },
                        new
                        {
                            Id = "",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 0,
                            Name = "都市計畫與空間資訊學系"
                        },
                        new
                        {
                            Id = "AhS7F9gUmxfbQ45agBzV6ZqyK",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 0,
                            Name = "土地管理學系"
                        },
                        new
                        {
                            Id = "qlJ5WI3YfX90fA4NKrt3EKXzI",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "土木工程學系"
                        },
                        new
                        {
                            Id = "mroQH0gDaaGHw3B31MDeWX2cO",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "水利工程與資源保育學系"
                        },
                        new
                        {
                            Id = "OD1yUIm1w5q3rV5VKxKZY6aJg",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "運輸與物流學系"
                        },
                        new
                        {
                            Id = "8CDofLpCA2z33Y4pXEKpPmCrf",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "都市計畫與空間資訊學系"
                        },
                        new
                        {
                            Id = "rm3BkevoEpzLf1eMVqE5Yo0ce",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "土地管理學系"
                        },
                        new
                        {
                            Id = "117awZ9RQvBTaStkYBP3jk9qL",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "景觀與遊憩碩士學位學程"
                        },
                        new
                        {
                            Id = "WucZWrsuYrvozv4TWeWJW61IU",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "專案管理碩士在職學位學程"
                        },
                        new
                        {
                            Id = "C3ps4hxYL8vu0hl6hpAcRYL7i",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "建設學院專案管理碩士在職專班"
                        },
                        new
                        {
                            Id = "zYc5qrrI7ZTyUdEY8mmOX2aN8",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "建設碩士在職學位學程"
                        },
                        new
                        {
                            Id = "J3ppFIMFhj8EuCGUOOmCP0bL6",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "智慧城市碩士學位學程"
                        },
                        new
                        {
                            Id = "Iw4sxzEHJ2ohiitIGz8RAPpoA",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 1,
                            Name = "西班牙薩拉戈薩大學物流供應鏈管理與創新創業雙碩士學位學程"
                        },
                        new
                        {
                            Id = "cbKctLMMlvmtYSLCDezoMWaDx",
                            CollegeId = "QGqpVsNzjcusLw2lisuECLEaT",
                            Degree = 2,
                            Name = "土木水利工程與建設規劃博士學位學程"
                        },
                        new
                        {
                            Id = "UvKL9QK7ThPRzLH7V8Zrp1Chu",
                            CollegeId = "iQJHwPwg4VAFwjXDJPVH2wtE0",
                            Degree = 0,
                            Name = "風險管理與保險學系"
                        },
                        new
                        {
                            Id = "z4sSzyyUCZGGcmj2hvL9y8XCf",
                            CollegeId = "iQJHwPwg4VAFwjXDJPVH2wtE0",
                            Degree = 0,
                            Name = "財務金融學系"
                        },
                        new
                        {
                            Id = "i5Fj90mDet7rvSsNYDPY5YU24",
                            CollegeId = "iQJHwPwg4VAFwjXDJPVH2wtE0",
                            Degree = 0,
                            Name = "財務工程與精算學士學位學程"
                        },
                        new
                        {
                            Id = "jKDRVp3ZfjFQsTIho96YUFmAj",
                            CollegeId = "iQJHwPwg4VAFwjXDJPVH2wtE0",
                            Degree = 1,
                            Name = "風險管理與保險學系"
                        },
                        new
                        {
                            Id = "PAkm3KYC60qsMU9o9xuczaz65",
                            CollegeId = "iQJHwPwg4VAFwjXDJPVH2wtE0",
                            Degree = 1,
                            Name = "財務金融學系"
                        },
                        new
                        {
                            Id = "pel3fUEJ3dUuTmhngqXuMARH7",
                            CollegeId = "iQJHwPwg4VAFwjXDJPVH2wtE0",
                            Degree = 1,
                            Name = "金融碩士在職學位學程"
                        },
                        new
                        {
                            Id = "o7HQY0mdOG2FCCMfPv3A0eiyU",
                            CollegeId = "iQJHwPwg4VAFwjXDJPVH2wtE0",
                            Degree = 1,
                            Name = "金融碩士在職專班"
                        },
                        new
                        {
                            Id = "b7Qo0Z5zzhREULXvVgAsQbawy",
                            CollegeId = "iQJHwPwg4VAFwjXDJPVH2wtE0",
                            Degree = 2,
                            Name = "金融博士學位學程"
                        },
                        new
                        {
                            Id = "ZGSzhoQ0SYpxasVopp9KRZha7",
                            CollegeId = "9xP6LTPTAcSWkRF6cx9Iq7cDv",
                            Degree = 0,
                            Name = "澳洲墨爾本皇家理工大學商學與創新雙學士學位學程"
                        },
                        new
                        {
                            Id = "YX6zcrayVMdPrflcZBZVF58BR",
                            CollegeId = "9xP6LTPTAcSWkRF6cx9Iq7cDv",
                            Degree = 0,
                            Name = "美國普渡大學電機資訊雙學士學位學程"
                        },
                        new
                        {
                            Id = "AawwxbqguYo02vgUmruY8q1H5",
                            CollegeId = "9xP6LTPTAcSWkRF6cx9Iq7cDv",
                            Degree = 0,
                            Name = "美國加州聖荷西州立大學商學大數據分析雙學士學位學程"
                        },
                        new
                        {
                            Id = "0IAQg7YRS9A2v1yDs3V6DS3fE",
                            CollegeId = "9xP6LTPTAcSWkRF6cx9Iq7cDv",
                            Degree = 0,
                            Name = "美國加州聖荷西州立大學工程雙學士學位學程"
                        },
                        new
                        {
                            Id = "mB10Nk6FneHFt04XuF84iJKc7",
                            CollegeId = "9xP6LTPTAcSWkRF6cx9Iq7cDv",
                            Degree = 0,
                            Name = "美國加州舊金山州立大學資訊工程雙學士學位學程"
                        },
                        new
                        {
                            Id = "a6VsUoLnqqvOYVFOOYZXP9vW6",
                            CollegeId = "9xP6LTPTAcSWkRF6cx9Iq7cDv",
                            Degree = 0,
                            Name = "國際雙學士學位學程"
                        },
                        new
                        {
                            Id = "Lxx5OqarnVEwetnl8RCX4oAdy",
                            CollegeId = "9xP6LTPTAcSWkRF6cx9Iq7cDv",
                            Degree = 1,
                            Name = "國際經營管理碩士學位學程"
                        },
                        new
                        {
                            Id = "nzgPilWPhn1M0OWMU3dirxo0P",
                            CollegeId = "woYRzMjOYVT0LlwVEvqarGaoS",
                            Degree = 0,
                            Name = "建築專業學院學士班"
                        },
                        new
                        {
                            Id = "yRkkVDq2xMAOV6meUnmb1O4iV",
                            CollegeId = "woYRzMjOYVT0LlwVEvqarGaoS",
                            Degree = 0,
                            Name = "建築學士學位學程"
                        },
                        new
                        {
                            Id = "aBP9gqZAzXx56nmIgKvFnDz3O",
                            CollegeId = "woYRzMjOYVT0LlwVEvqarGaoS",
                            Degree = 0,
                            Name = "創新設計學士學位學程"
                        },
                        new
                        {
                            Id = "IKoM8CjCMFhQIkxBq3VPnMMp9",
                            CollegeId = "woYRzMjOYVT0LlwVEvqarGaoS",
                            Degree = 0,
                            Name = "室內設計學士學位學程"
                        },
                        new
                        {
                            Id = "TpmRpkDFfhrtlg14kuI55C29i",
                            CollegeId = "woYRzMjOYVT0LlwVEvqarGaoS",
                            Degree = 0,
                            Name = "室內設計進修學士班"
                        },
                        new
                        {
                            Id = "yXJHEN90oBLQmE5rmnVgFP88G",
                            CollegeId = "woYRzMjOYVT0LlwVEvqarGaoS",
                            Degree = 1,
                            Name = "建築碩士學位學程"
                        },
                        new
                        {
                            Id = "oQnr4w8CM9SqRcM75XIOJhfNc",
                            CollegeId = "woYRzMjOYVT0LlwVEvqarGaoS",
                            Degree = 1,
                            Name = "建築碩士在職學位學程"
                        },
                        new
                        {
                            Id = "Dm3w09uagkM33e8ZrKJjWyk1p",
                            CollegeId = "woYRzMjOYVT0LlwVEvqarGaoS",
                            Degree = 1,
                            Name = "創意設計碩士學位學程"
                        },
                        new
                        {
                            Id = "4d9tHiUYHz5Xe7Wzepc6RShZ7",
                            CollegeId = "ggRSStSxsHsmiT3yvftunUmCm",
                            Degree = 0,
                            Name = "人工智慧技術與應用學士學位學程"
                        });
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Alumnus", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfGraduation")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Alumni");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Staff", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationRoleClaim", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserClaim", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserLogin", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserToken", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.School.Department", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.School.College", "College")
                        .WithMany("Departments")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Alumnus", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithOne("Alumnus")
                        .HasForeignKey("TsheThauLoo.Entities.User.Alumnus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Employee", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithOne("Employee")
                        .HasForeignKey("TsheThauLoo.Entities.User.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TsheThauLoo.Entities.User.Substitute", "Substitute", b1 =>
                        {
                            b1.Property<string>("EmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Division")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Substitute")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Staff", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithOne("Staff")
                        .HasForeignKey("TsheThauLoo.Entities.User.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Student", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithOne("Student")
                        .HasForeignKey("TsheThauLoo.Entities.User.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationRole", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Alumnus");

                    b.Navigation("Claims");

                    b.Navigation("Employee");

                    b.Navigation("Logins");

                    b.Navigation("Staff");

                    b.Navigation("Student");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.School.College", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
