// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TsheThauLoo.Data;

#nullable disable

namespace TsheThauLoo.Data.Migrations
{
    [DbContext(typeof(TsheThauLooDbContext))]
    partial class TsheThauLooDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.School.College", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Colleges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Name = "工程與科學學院"
                        },
                        new
                        {
                            Id = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Name = "商學院"
                        },
                        new
                        {
                            Id = "a89c9f64-6562-44b9-b744-fc1050c575e5",
                            Name = "經營管理學院"
                        },
                        new
                        {
                            Id = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Name = "人文社會學院"
                        },
                        new
                        {
                            Id = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Name = "資訊電機學院"
                        },
                        new
                        {
                            Id = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Name = "建設學院"
                        },
                        new
                        {
                            Id = "1ce0231c-283c-4636-979b-ba143fa42b62",
                            Name = "金融學院"
                        },
                        new
                        {
                            Id = "227f18d6-d050-4147-aedd-ba775a71a292",
                            Name = "國際科技與管理學院"
                        },
                        new
                        {
                            Id = "8f0bd676-a08b-43e1-a4bb-4f32dbf8174f",
                            Name = "建築專業學院"
                        },
                        new
                        {
                            Id = "3041f226-9230-4756-935d-8e0fc1ed112d",
                            Name = "創能學院"
                        });
                });

            modelBuilder.Entity("TsheThauLoo.Entities.School.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("CollegeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("Degree")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "54a533be-ab21-4c64-8d4c-98b8f65ef77b",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 0,
                            Name = "機械與電腦輔助工程學系"
                        },
                        new
                        {
                            Id = "4ab35fc1-d012-44ae-a3a7-aa5f9333ab91",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 0,
                            Name = "纖維與複合材料學系"
                        },
                        new
                        {
                            Id = "efdd3c62-e7d0-4ba4-bb60-a5868ecc95f5",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 0,
                            Name = "工業工程與系統管理學系"
                        },
                        new
                        {
                            Id = "4d969aab-d6fc-4ca3-be20-5f71fd3e22ba",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 0,
                            Name = "化學工程學系"
                        },
                        new
                        {
                            Id = "e38a5833-4636-4ebf-944c-eb235568b05f",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 0,
                            Name = "應用數學系"
                        },
                        new
                        {
                            Id = "86bc1a5e-0543-48a4-9d88-786e5e49b5b5",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 0,
                            Name = "航太與系統工程學系"
                        },
                        new
                        {
                            Id = "829d2e71-7b53-4080-ba86-b82defea9099",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 0,
                            Name = "環境工程與科學學系"
                        },
                        new
                        {
                            Id = "577e5175-c71b-4b17-890a-0f2733a4ca7c",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 0,
                            Name = "材料科學與工程學系"
                        },
                        new
                        {
                            Id = "5684f51e-7506-43d4-9253-c8b60912653d",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 0,
                            Name = "光電科學與工程學系"
                        },
                        new
                        {
                            Id = "da19b793-5507-4363-9c82-c8779cad9a98",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 0,
                            Name = "精密系統設計學士學位學程"
                        },
                        new
                        {
                            Id = "119e1c67-f803-4dc3-959b-a0673220c71c",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "機械與電腦輔助工程學系"
                        },
                        new
                        {
                            Id = "e74167e7-bfe8-49f1-96d0-60bd76cb346c",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "纖維與複合材料學系"
                        },
                        new
                        {
                            Id = "de446c35-bc1b-4df8-a471-f46ef2f7df27",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "工業工程與系統管理學系"
                        },
                        new
                        {
                            Id = "c9e56c0e-2cff-459d-90ad-9efea62403e2",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "化學工程學系"
                        },
                        new
                        {
                            Id = "e3c5d5cf-14ee-4019-92ee-11300a5572c6",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "數據科學碩士學位學程"
                        },
                        new
                        {
                            Id = "4b70a8b9-55cc-4c59-961a-3e2e45205001",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "航太與系統工程學系"
                        },
                        new
                        {
                            Id = "593441cb-d226-4a17-9f44-f43ed4ad3304",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "環境工程與科學學系"
                        },
                        new
                        {
                            Id = "4bd31f0a-0e32-42bc-bd3d-369b2734e4d6",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "材料科學與工程學系"
                        },
                        new
                        {
                            Id = "56582cf6-842d-47bb-a584-cb116e913690",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "光電科學與工程學系"
                        },
                        new
                        {
                            Id = "dfb33024-0039-4abc-ba22-4f33c5f541b7",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "電聲碩士學位學程"
                        },
                        new
                        {
                            Id = "9f7b6093-a30c-43f6-9b80-e65b919c26ae",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "綠色能源科技碩士學位學程"
                        },
                        new
                        {
                            Id = "0753a654-47eb-417d-ace0-9e8ebd6a814c",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "智能製造與工程管理碩士在職學位學程"
                        },
                        new
                        {
                            Id = "3f07e6c0-36ea-4b4d-8793-74dcb1cadb7e",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 1,
                            Name = "應用數學系"
                        },
                        new
                        {
                            Id = "36d94909-69ac-4f83-a541-54e5c02edd5f",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 2,
                            Name = "材料科學與工程學系"
                        },
                        new
                        {
                            Id = "7701b7ae-1dfa-459b-9490-129b6ea80f7f",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 2,
                            Name = "化學工程學系"
                        },
                        new
                        {
                            Id = "8a40ac5d-f752-41ec-8546-2d320515e62b",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 2,
                            Name = "纖維與複合材料學系"
                        },
                        new
                        {
                            Id = "0aec387a-093b-4dc0-a9b8-21a684c94d95",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 2,
                            Name = "環境工程與科學學系"
                        },
                        new
                        {
                            Id = "0a05fc3d-08a2-42e0-aeda-1efac68e94b5",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 2,
                            Name = "機械與航空工程博士學位學程"
                        },
                        new
                        {
                            Id = "5894f2e6-09c3-4808-83fe-f28b170bc9ca",
                            CollegeId = "3e22a96f-c909-4c79-a903-8c0fef6c789a",
                            Degree = 2,
                            Name = "工業工程與系統管理學系"
                        },
                        new
                        {
                            Id = "266c7fd6-474e-43dc-8897-ea3bc31a8e0d",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "會計學系"
                        },
                        new
                        {
                            Id = "4e1cd01d-94bd-42de-807b-2db5ad803059",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "企業管理學系"
                        },
                        new
                        {
                            Id = "f9f38b0b-a95c-41a7-afb4-14bcfc3b00ae",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "國際經營與貿易學系"
                        },
                        new
                        {
                            Id = "fd6d4884-2a28-4184-97ef-5af41f91aab6",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "財稅學系"
                        },
                        new
                        {
                            Id = "1faab6e3-45e9-4f2a-b9c6-d515a80ee74e",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "統計學系"
                        },
                        new
                        {
                            Id = "14f08a09-0f6d-4a8c-aa7a-31999d32ab94",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "經濟學系"
                        },
                        new
                        {
                            Id = "567323ad-82f1-4531-b430-c6d0efb4b3dd",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "合作經濟暨社會事業經營學系"
                        },
                        new
                        {
                            Id = "1d50af56-b8e1-4aef-b19f-b6954e3223c5",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "行銷學系"
                        },
                        new
                        {
                            Id = "86f378ce-6114-4808-952c-07668dbaf9fd",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "國際企業管理全英語學士學位學程"
                        },
                        new
                        {
                            Id = "45436abe-74f2-45f2-a2f5-93c931cdf121",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "商學進修學士學位學程"
                        },
                        new
                        {
                            Id = "b64bc109-a3c4-4aee-b581-5d6cdcb3ab0d",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 0,
                            Name = "商學進修學士班"
                        },
                        new
                        {
                            Id = "bbb9d4b7-bc53-4385-8ce5-a2913be97bcc",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "會計學系"
                        },
                        new
                        {
                            Id = "cc3a263f-efff-4abc-8088-281a61a9c571",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "企業管理學系"
                        },
                        new
                        {
                            Id = "4777fce8-c37d-43a4-9428-60abafbeb128",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "國際經營與貿易學系"
                        },
                        new
                        {
                            Id = "037122b4-04e7-4666-a9f4-4cbaf3b1790a",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "財稅學系"
                        },
                        new
                        {
                            Id = "6046654d-8b50-4915-ba2b-e649ea32913f",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "統計學系"
                        },
                        new
                        {
                            Id = "70488f20-cd2d-4b88-90e3-93cbab0c46a2",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "經濟學系"
                        },
                        new
                        {
                            Id = "49cac5bf-6920-4b47-a3a4-ba794f692515",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "合作經濟暨社會事業經營學系"
                        },
                        new
                        {
                            Id = "57de29ef-f94c-4ade-bf49-3148c6668b72",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "行銷學系"
                        },
                        new
                        {
                            Id = "51b58c88-e5e6-4112-a2ea-f3ffd5018669",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "財經法律研究所"
                        },
                        new
                        {
                            Id = "08392375-344e-472d-a4e1-e0dce298f3b5",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "科技管理碩士學位學程"
                        },
                        new
                        {
                            Id = "675390ab-fcad-4817-9868-a77bdf6b2e78",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "商學專業碩士在職學位學程"
                        },
                        new
                        {
                            Id = "2daa2f2f-c287-473b-b0cf-05fa1ffb7e13",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 1,
                            Name = "商學院商學專業碩士在職專班"
                        },
                        new
                        {
                            Id = "de2fa011-c6d4-4fe3-8f09-4f3bbc8c476f",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 2,
                            Name = "統計學系"
                        },
                        new
                        {
                            Id = "e203228a-8b3a-4e80-9272-349513e60b5d",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 2,
                            Name = "經濟學系"
                        },
                        new
                        {
                            Id = "c0e7ee82-ca03-4327-93c3-cfa7af9f69b7",
                            CollegeId = "13c57893-16db-478f-9b65-264ccb4898e6",
                            Degree = 2,
                            Name = "商學博士學位學程"
                        },
                        new
                        {
                            Id = "5aa9154a-de0a-4e15-8d73-855f570a8517",
                            CollegeId = "a89c9f64-6562-44b9-b744-fc1050c575e5",
                            Degree = 1,
                            Name = "經營管理碩士在職學位學程"
                        },
                        new
                        {
                            Id = "f0b0b676-0117-4fa3-921b-f075f694dff5",
                            CollegeId = "a89c9f64-6562-44b9-b744-fc1050c575e5",
                            Degree = 1,
                            Name = "經營管理碩士在職專班"
                        },
                        new
                        {
                            Id = "2d3d53f4-2f7c-481c-b6bb-6813839a69eb",
                            CollegeId = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Degree = 0,
                            Name = "中國文學系"
                        },
                        new
                        {
                            Id = "ed0b6594-3e17-4c5a-8b61-232b2eb5d15d",
                            CollegeId = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Degree = 0,
                            Name = "外國語文學系"
                        },
                        new
                        {
                            Id = "6ae91071-ab05-4eca-94d5-fd2f89362e53",
                            CollegeId = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Degree = 0,
                            Name = "人文社會學士學位學程"
                        },
                        new
                        {
                            Id = "9af2920a-888b-4d66-8ba8-79816b4cf9a8",
                            CollegeId = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Degree = 1,
                            Name = "中國文學系"
                        },
                        new
                        {
                            Id = "5f683b1e-ffa1-48d3-a8bc-43740a755505",
                            CollegeId = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Degree = 1,
                            Name = "外國語文學系"
                        },
                        new
                        {
                            Id = "236e7e9d-dc6c-441a-96b1-7f89a42293e5",
                            CollegeId = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Degree = 1,
                            Name = "歷史與文物研究所"
                        },
                        new
                        {
                            Id = "a8fe8fe4-fecf-427d-8599-5150354cbb5a",
                            CollegeId = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Degree = 1,
                            Name = "公共事務與社會創新研究所"
                        },
                        new
                        {
                            Id = "e6b2f684-37ef-43ee-a166-edd71f4cdd9c",
                            CollegeId = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Degree = 1,
                            Name = "文化與社會創新碩士學位學程"
                        },
                        new
                        {
                            Id = "9aa5dd68-26e8-4abe-959a-340539a4603a",
                            CollegeId = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Degree = 1,
                            Name = "公共事務與社會創新碩士在職學位學程"
                        },
                        new
                        {
                            Id = "42946f30-e417-4347-b93e-f8fdfb8a34ad",
                            CollegeId = "d8458f4f-6a6a-4bad-97ee-6d1ce9aaf93a",
                            Degree = 2,
                            Name = "中國文學系"
                        },
                        new
                        {
                            Id = "b40215ab-2609-4464-b24e-bdfbc5d3ed2b",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 0,
                            Name = "資訊工程學系"
                        },
                        new
                        {
                            Id = "2bbc4650-a47f-45a9-a220-b41f976011e5",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 0,
                            Name = "電子工程學系"
                        },
                        new
                        {
                            Id = "f89178cf-ab6c-4a6c-b5f0-b3d2f2a4aaa7",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 0,
                            Name = "電機工程學系"
                        },
                        new
                        {
                            Id = "f2d5a4bd-df73-44eb-8383-7fccfafa6307",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 0,
                            Name = "自動控制工程學系"
                        },
                        new
                        {
                            Id = "658b7def-5592-45c5-9059-5628034e3d59",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 0,
                            Name = "通訊工程學系"
                        },
                        new
                        {
                            Id = "621e0eb8-1bd2-4669-b6e7-43eed1596a1c",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 0,
                            Name = "資訊電機學院學士班"
                        },
                        new
                        {
                            Id = "367992b7-f691-4337-aade-f02336ea9859",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 1,
                            Name = "資訊工程學系"
                        },
                        new
                        {
                            Id = "5f3f21fb-3adf-4ca4-aef0-4cfd968c1f57",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 1,
                            Name = "電子工程學系"
                        },
                        new
                        {
                            Id = "ebdfb8e8-7a8d-495c-9429-12333ed77008",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 1,
                            Name = "電機工程學系"
                        },
                        new
                        {
                            Id = "47f0dab8-4507-491a-8871-f057d856c55e",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 1,
                            Name = "自動控制工程學系"
                        },
                        new
                        {
                            Id = "d77a826e-736f-49b6-8987-f4df06a71cf7",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 1,
                            Name = "通訊工程學系"
                        },
                        new
                        {
                            Id = "05d8034e-7a32-4244-af88-a8e82885c002",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 1,
                            Name = "生醫資訊暨生醫工程碩士學位學程"
                        },
                        new
                        {
                            Id = "bc526bfb-6db9-44c0-bb88-44641663c933",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 1,
                            Name = "光電能源與視覺科技碩士在職專班"
                        },
                        new
                        {
                            Id = "52629b36-cb7c-4c34-af93-0f5b34110bd2",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 1,
                            Name = "視光科技碩士在職學位學程"
                        },
                        new
                        {
                            Id = "b404fded-a6bd-4648-93ff-32568b51c8b3",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 1,
                            Name = "資訊電機工程碩士在職學位學程"
                        },
                        new
                        {
                            Id = "de8c85e8-e2e2-4b66-850d-6559189448dc",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 1,
                            Name = "資訊電機工程碩士在職專班"
                        },
                        new
                        {
                            Id = "0db86b82-81ca-42ed-bc5f-a18ebbab6924",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 2,
                            Name = "資訊工程學系"
                        },
                        new
                        {
                            Id = "ddde37e7-e11d-4006-9255-684e21ae97dd",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 2,
                            Name = "電機與通訊工程博士學位學程"
                        },
                        new
                        {
                            Id = "b33110d1-3c0d-491f-9cc3-a05bdff11f4d",
                            CollegeId = "fa044fea-06d3-4f0e-a354-f335d761e2cb",
                            Degree = 2,
                            Name = "智慧聯網產業博士學位學程"
                        },
                        new
                        {
                            Id = "825646bc-8423-46ce-af79-169660dd2571",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 0,
                            Name = "土木工程學系"
                        },
                        new
                        {
                            Id = "e04de454-4806-4537-b90d-efee36d7e9cc",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 0,
                            Name = "水利工程與資源保育學系"
                        },
                        new
                        {
                            Id = "629fd6d4-f81e-43f3-951c-d63e5ab9a78d",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 0,
                            Name = "運輸與物流學系"
                        },
                        new
                        {
                            Id = "eaec0302-ce47-4e35-9a64-13e4c34cb289",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 0,
                            Name = "都市計畫與空間資訊學系"
                        },
                        new
                        {
                            Id = "49635313-4992-4e22-b1a6-192127777ee6",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 0,
                            Name = "土地管理學系"
                        },
                        new
                        {
                            Id = "e9001f5e-88a5-4aea-9acc-d3e5c471c306",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "土木工程學系"
                        },
                        new
                        {
                            Id = "3d788520-2708-433c-ab8a-9ffbd647faf5",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "水利工程與資源保育學系"
                        },
                        new
                        {
                            Id = "bb7be155-823c-4337-90d3-1db9a587cb3e",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "運輸與物流學系"
                        },
                        new
                        {
                            Id = "2bbeb586-7c3f-4e17-ad2f-4d94b6adc796",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "都市計畫與空間資訊學系"
                        },
                        new
                        {
                            Id = "e3efe1d5-cc62-4b76-bab4-23597d6e73e4",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "土地管理學系"
                        },
                        new
                        {
                            Id = "6ff1a064-845c-4ca5-840a-ca29694592c5",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "景觀與遊憩碩士學位學程"
                        },
                        new
                        {
                            Id = "0ebdf6ea-88f1-499f-88ae-f6d3646d92af",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "專案管理碩士在職學位學程"
                        },
                        new
                        {
                            Id = "86e3f7a6-b12c-4c08-8733-aa125de779b9",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "建設學院專案管理碩士在職專班"
                        },
                        new
                        {
                            Id = "f25888dc-8728-40a3-bd08-23f7e048a1d7",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "建設碩士在職學位學程"
                        },
                        new
                        {
                            Id = "b1bae1c5-6b9f-41de-b42f-cd82a7dad8f2",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "智慧城市碩士學位學程"
                        },
                        new
                        {
                            Id = "576d232b-0660-4156-918f-a55e24c9ca99",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 1,
                            Name = "西班牙薩拉戈薩大學物流供應鏈管理與創新創業雙碩士學位學程"
                        },
                        new
                        {
                            Id = "c134861a-3f57-4f83-a0b0-ea79024a96c8",
                            CollegeId = "f07974ca-3ef4-4166-a5ea-60b19980c05e",
                            Degree = 2,
                            Name = "土木水利工程與建設規劃博士學位學程"
                        },
                        new
                        {
                            Id = "db06de5e-6308-4d04-a10e-aa174e32d17d",
                            CollegeId = "1ce0231c-283c-4636-979b-ba143fa42b62",
                            Degree = 0,
                            Name = "風險管理與保險學系"
                        },
                        new
                        {
                            Id = "2ccfe6b4-06fc-47d9-9c1b-82a501fa1058",
                            CollegeId = "1ce0231c-283c-4636-979b-ba143fa42b62",
                            Degree = 0,
                            Name = "財務金融學系"
                        },
                        new
                        {
                            Id = "4f8e93da-b82e-48da-b543-f3a524d6113c",
                            CollegeId = "1ce0231c-283c-4636-979b-ba143fa42b62",
                            Degree = 0,
                            Name = "財務工程與精算學士學位學程"
                        },
                        new
                        {
                            Id = "fad8311c-37be-4e8a-a31b-81b0323db9c9",
                            CollegeId = "1ce0231c-283c-4636-979b-ba143fa42b62",
                            Degree = 1,
                            Name = "風險管理與保險學系"
                        },
                        new
                        {
                            Id = "41496773-ee83-4cdf-b60d-bacc7689b9c0",
                            CollegeId = "1ce0231c-283c-4636-979b-ba143fa42b62",
                            Degree = 1,
                            Name = "財務金融學系"
                        },
                        new
                        {
                            Id = "db431a07-9a7b-412c-9fb2-9ddbf7f29ac1",
                            CollegeId = "1ce0231c-283c-4636-979b-ba143fa42b62",
                            Degree = 1,
                            Name = "金融碩士在職學位學程"
                        },
                        new
                        {
                            Id = "76b83e56-7c5b-4595-97b1-49ea6106d2cf",
                            CollegeId = "1ce0231c-283c-4636-979b-ba143fa42b62",
                            Degree = 1,
                            Name = "金融碩士在職專班"
                        },
                        new
                        {
                            Id = "08dd0723-8c09-4b5c-b4e4-86d48b8bb144",
                            CollegeId = "1ce0231c-283c-4636-979b-ba143fa42b62",
                            Degree = 2,
                            Name = "金融博士學位學程"
                        },
                        new
                        {
                            Id = "c742d386-401e-44aa-8b3e-892f407ee6fc",
                            CollegeId = "227f18d6-d050-4147-aedd-ba775a71a292",
                            Degree = 0,
                            Name = "澳洲墨爾本皇家理工大學商學與創新雙學士學位學程"
                        },
                        new
                        {
                            Id = "335b234b-d7d4-4c55-840e-0e83d57da5cb",
                            CollegeId = "227f18d6-d050-4147-aedd-ba775a71a292",
                            Degree = 0,
                            Name = "美國普渡大學電機資訊雙學士學位學程"
                        },
                        new
                        {
                            Id = "8cbe768c-3397-4251-b784-49dd8e6e99cf",
                            CollegeId = "227f18d6-d050-4147-aedd-ba775a71a292",
                            Degree = 0,
                            Name = "美國加州聖荷西州立大學商學大數據分析雙學士學位學程"
                        },
                        new
                        {
                            Id = "0b4046c5-ff28-4b77-bd47-262b7def018d",
                            CollegeId = "227f18d6-d050-4147-aedd-ba775a71a292",
                            Degree = 0,
                            Name = "美國加州聖荷西州立大學工程雙學士學位學程"
                        },
                        new
                        {
                            Id = "dc259920-dee3-48bd-8867-0a385abbadbe",
                            CollegeId = "227f18d6-d050-4147-aedd-ba775a71a292",
                            Degree = 0,
                            Name = "美國加州舊金山州立大學資訊工程雙學士學位學程"
                        },
                        new
                        {
                            Id = "30b602f3-6586-4f43-99ae-bdef268d0b64",
                            CollegeId = "227f18d6-d050-4147-aedd-ba775a71a292",
                            Degree = 0,
                            Name = "國際雙學士學位學程"
                        },
                        new
                        {
                            Id = "21879ce1-3894-4d02-97d3-b222a21b439c",
                            CollegeId = "227f18d6-d050-4147-aedd-ba775a71a292",
                            Degree = 1,
                            Name = "國際經營管理碩士學位學程"
                        },
                        new
                        {
                            Id = "599a3556-ba31-460e-9922-ba345f9b83e6",
                            CollegeId = "8f0bd676-a08b-43e1-a4bb-4f32dbf8174f",
                            Degree = 0,
                            Name = "建築專業學院學士班"
                        },
                        new
                        {
                            Id = "5336690e-f31c-4c33-837a-8be30a4a7ceb",
                            CollegeId = "8f0bd676-a08b-43e1-a4bb-4f32dbf8174f",
                            Degree = 0,
                            Name = "建築學士學位學程"
                        },
                        new
                        {
                            Id = "9dfcf85b-65da-4691-a864-ea1e478ec960",
                            CollegeId = "8f0bd676-a08b-43e1-a4bb-4f32dbf8174f",
                            Degree = 0,
                            Name = "創新設計學士學位學程"
                        },
                        new
                        {
                            Id = "0b7b6c54-59c8-4eb7-a47d-477572bf464c",
                            CollegeId = "8f0bd676-a08b-43e1-a4bb-4f32dbf8174f",
                            Degree = 0,
                            Name = "室內設計學士學位學程"
                        },
                        new
                        {
                            Id = "e67f99e3-92de-441c-b60b-9bea2901dad4",
                            CollegeId = "8f0bd676-a08b-43e1-a4bb-4f32dbf8174f",
                            Degree = 0,
                            Name = "室內設計進修學士班"
                        },
                        new
                        {
                            Id = "6b9b4a9c-22bd-4deb-86b7-c7bc1705703d",
                            CollegeId = "8f0bd676-a08b-43e1-a4bb-4f32dbf8174f",
                            Degree = 1,
                            Name = "建築碩士學位學程"
                        },
                        new
                        {
                            Id = "fc45c859-3016-494d-b878-257e8c4007a2",
                            CollegeId = "8f0bd676-a08b-43e1-a4bb-4f32dbf8174f",
                            Degree = 1,
                            Name = "建築碩士在職學位學程"
                        },
                        new
                        {
                            Id = "03492289-e244-4aa9-90ff-58190616ab12",
                            CollegeId = "8f0bd676-a08b-43e1-a4bb-4f32dbf8174f",
                            Degree = 1,
                            Name = "創意設計碩士學位學程"
                        },
                        new
                        {
                            Id = "25c0ee9a-c2fe-480b-9526-61f01f68d527",
                            CollegeId = "3041f226-9230-4756-935d-8e0fc1ed112d",
                            Degree = 0,
                            Name = "人工智慧技術與應用學士學位學程"
                        });
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Alumnus", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfGraduation")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Alumni", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Staff", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Staffs", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationRoleClaim", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserClaim", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserLogin", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUserToken", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.School.Department", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.School.College", "College")
                        .WithMany("Departments")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Alumnus", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithOne("Alumnus")
                        .HasForeignKey("TsheThauLoo.Entities.User.Alumnus", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Employee", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithOne("Employee")
                        .HasForeignKey("TsheThauLoo.Entities.User.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TsheThauLoo.Entities.User.Employee.Substitute#TsheThauLoo.Entities.User.Substitute", "Substitute", b1 =>
                        {
                            b1.Property<string>("EmployeeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Division")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Substitute")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Staff", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithOne("Staff")
                        .HasForeignKey("TsheThauLoo.Entities.User.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.User.Student", b =>
                {
                    b.HasOne("TsheThauLoo.Entities.Identity.ApplicationUser", "User")
                        .WithOne("Student")
                        .HasForeignKey("TsheThauLoo.Entities.User.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationRole", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Alumnus");

                    b.Navigation("Claims");

                    b.Navigation("Employee");

                    b.Navigation("Logins");

                    b.Navigation("Staff");

                    b.Navigation("Student");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TsheThauLoo.Entities.School.College", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
